# TODO: revert to node:20 when possible
# look out for TypeError: Cannot redefine property: File

FROM node:18-bullseye-slim

WORKDIR /usr/src/app
COPY package*.json package-lock*.json ./
RUN npm install
COPY --chown=node:node . .

CMD ["npm", "run", "dev"]