version: "3.9"

services:
  api:
    image: "c1re/propel-service"
    env_file: .env
    restart: always
  nginx:
    image: "c1re/propel-nginx"
    volumes:
      - /etc/pki/tls/certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
