version: "3.9"

services:
  client:
    image: client-prod
    container_name: client-prod
    build:
      context: ./client
      dockerfile: Dockerfile
  api:
    image: server-prod
    container_name: server-prod
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
  nginx:
    image: nginx-prod
    container_name: nginx-prod
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 9090:80
    restart: always
    depends_on:
      - client
      - api
