version: "3.9"

services:
  client:
    image: client-prod
    container_name: client-prod
    build:
      context: ./client
      dockerfile: Dockerfile
  server:
    image: server-prod
    container_name: server-prod
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
  nginx:
    image: nginx:stable-alpine3.17-slim
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9090:90
    restart: unless-stopped
    depends_on:
      - client
      - server
