FROM node:18-bullseye-slim as base

# ----- prune -----

FROM base as prune

WORKDIR /app
RUN npm install -g turbo
COPY . .
RUN turbo prune server --docker

# ----- installer and runner -----

FROM base as installer

RUN npm install -g dotenv-cli

WORKDIR /app

COPY --from=prune /app/out/json .
COPY --from=prune /app/out/package-lock.json ./package-lock.json
RUN npm install

COPY --from=prune /app/out/full/ .
COPY turbo.json turbo.json

CMD npm run migrate:local --workspace=@propel/drizzle && npx turbo dev --filter=server
# ^ migrate after docker network init