export enum ENV {
  NODE_ENV = "NODE_ENV",
  RESEND_KEY = "RESEND_KEY",
  RECOVERY_EMAIL = "RECOVERY_EMAIL",
  VERIFY_EMAIL = "VERIFY_EMAIL",
  PG_URL = "PG_URL",
  REDIS_HOST = "REDIS_HOST",
  REDIS_PW = "REDIS_PW",
  REDIS_USERNAME = "REDIS_USERNAME",
  REDIS_PORT = "REDIS_PORT",
  TESTMAIL_ENDPOINT = "TESTMAIL_ENDPOINT",
  TESTMAIL_NAMESPACE = "TESTMAIL_NAMESPACE",
  IDLE_SESSION_COOKIE = "IDLE_SESSION_COOKIE",
  IDLE_SESSION_LENGTH = "IDLE_SESSION_LENGTH",
  ABSOLUTE_SESSION_COOKIE = "ABSOLUTE_SESSION_COOKIE",
  ABSOLUTE_SESSION_LENGTH = "ABSOLUTE_SESSION_LENGTH",
  PRE_AUTH_SESSION_COOKIE = "PRE_AUTH_SESSION_COOKIE",
  PRE_AUTH_SESSION_LENGTH = "PRE_AUTH_SESSION_LENGTH",
  CSRF_COOKIE = "CSRF_COOKIE",
  CSRF_SECRET = "CSRF_SECRET",
  PRE_AUTH_CSRF_SECRET = "PRE_AUTH_CSRF_SECRET",
  COOKIE_SECRET = "COOKIE_SECRET",
  SALT_ROUNDS = "SALT_ROUNDS",
  ONE_HOUR = "ONE_HOUR",
}

export enum CONFIG {
  resendKey = "email.resendKey",
  recoveryEmail = "email.recoveryEmail",
  verifyEmail = "email.verifyEmail",
  postgresUrl = "postgres.url",
  idleSessionLength = "session.idleLength",
  absoluteSessionLength = "session.absoluteLength",
  preAuthSessionLength = "session.preAuthLength",
  redisHost = "redis.host",
  redisPassword = "redis.password",
  redisUsername = "redis.username",
  redisPort = "redis.port",
  csrfSecret = "secret.csrf",
  preAuthCsrfSecret = "secret.preAuthCsrf",
  cookieSecret = "secret.cookie",
}

export enum DEFAULT {
  IDLE_SESSION_LENGTH = "1800000",
  PRE_AUTH_SESSION_LENGTH = "3600000",
  ABSOLUTE_SESSION_LENGTH = "28800000",
  SALT_ROUNDS = "7",
  IDLE_SESSION_COOKIE = "idle-propel-session",
  ABSOLUTE_SESSION_COOKIE = "absolute-propel-session",
  PRE_AUTH_SESSION_COOKIE = "pre-auth-session",
  ONE_HOUR = 3600000,
}
