FROM node:18-alpine as base

# -- builder --

FROM base as builder

RUN apk add --no-cache libc6-compat
RUN apk update

WORKDIR /usr/src/app
RUN npm install -g turbo
COPY . .
RUN turbo prune client --docker

# -- installer --

FROM base as installer

RUN apk add --no-cache libc6-compat
RUN apk update

WORKDIR /usr/src/app
COPY .gitignore .gitignore
COPY --from=builder /usr/src/app/out/json/ .
COPY --from=builder /usr/src/app/out/package-lock.json ./package-lock.json
RUN npm install

CMD npx turbo run dev --scope=client --include-dependencies --no-deps

# COPY --from=builder /usr/src/app/out/full/ .
# COPY turbo.json turbo.json

# ------------- previous dockerfile below

# TODO: revert to node:20 when possible
# look out for TypeError: Cannot redefine property: File

# FROM node:18-bullseye-slim

# WORKDIR /usr/src/app
# COPY package*.json package-lock*.json ./
# RUN npm install
# COPY --chown=node:node . .

# CMD ["npm", "run", "dev"]