# use this to build production images for pushing to Docker Hub
version: "3.9"

services:
  api:
    image: server-prod
    container_name: server-prod
    build:
      context: ../
      dockerfile: ./apps/server/Dockerfile
  nginx:
    image: nginx-prod
    container_name: nginx-prod
    build:
      context: ../
      dockerfile: ./packages/nginx/docker/Dockerfile
    ports:
      - 80:80
      - 443:443
