version: "3.9"

services:
  client:
    image: client-prod
    container_name: client-prod
    logging:
      driver: none
    build:
      context: ../
      dockerfile: ./apps/client/Dockerfile
  api:
    extends:
      file: docker-compose.common.yml
      service: server-prod
    environment:
      PG_URL: ${PG_URL}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PW: ${REDIS_PW}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_HOST: ${REDIS_HOST}
      IDLE_SESSION_LENGTH: ${IDLE_SESSION_LENGTH}
      ABSOLUTE_SESSION_LENGTH: ${ABSOLUTE_SESSION_LENGTH}
      PRE_AUTH_SESSION_LENGTH: ${PRE_AUTH_SESSION_LENGTH}
      CSRF_SECRET: ${CSRF_SECRET}
      PRE_AUTH_CSRF_SECRET: ${PRE_AUTH_CSRF_SECRET}
      COOKIE_SECRET: ${COOKIE_SECRET}
      SALT_ROUNDS: ${SALT_ROUNDS}
      RESEND_KEY: ${RESEND_KEY}
      RECOVERY_EMAIL: ${RECOVERY_EMAIL}
      VERIFY_EMAIL: ${VERIFY_EMAIL}
      TESTMAIL_KEY: ${TESTMAIL_KEY}
      TESTMAIL_ENDPOINT: ${TESTMAIL_ENDPOINT}
      TESTMAIL_NAMESPACE: ${TESTMAIL_NAMESPACE}
  nginx:
    extends:
      file: docker-compose.common.yml
      service: preview-nginx
    ports:
      - 9090:80
    depends_on:
      - client
      - api
