version: "3.9"

services:
  db:
    extends:
      file: docker-compose.common.yml
      service: db
    tty: true
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    extends:
      file: docker-compose.common.yml
      service: redis
    ports:
      - 6379:6379
  client:
    image: client-dev
    container_name: client-dev
    build:
      context: ../
      dockerfile: ./apps/client/Dockerfile.dev
    volumes:
      - ../:/app
      - /app/node_modules
  server:
    image: server-dev
    container_name: server-dev
    build:
      context: ../
      dockerfile: ./apps/server/Dockerfile.dev
    env_file:
      - ../apps/server/.env.development
    #environment:
    #  RESEND_KEY: ${RESEND_KEY}
    #  RECOVERY_EMAIL: ${RECOVERY_EMAIL}
    #  VERIFY_EMAIL: ${VERIFY_EMAIL}
    #  PG_URL: ${PG_URL}
    #  REDIS_HOST: ${REDIS_HOST}
    #  REDIS_PORT: ${REDIS_PORT}
    #  IDLE_SESSION_LENGTH: ${IDLE_SESSION_LENGTH}
    #  ABSOLUTE_SESSION_LENGTH: ${ABSOLUTE_SESSION_LENGTH}
    #  PRE_AUTH_SESSION_LENGTH: ${PRE_AUTH_SESSION_LENGTH}
    #  CSRF_SECRET: ${CSRF_SECRET}
    #  PRE_AUTH_CSRF_SECRET: ${PRE_AUTH_CSRF_SECRET}
    #  COOKIE_SECRET: ${COOKIE_SECRET}
    #  SALT_ROUNDS: ${SALT_ROUNDS}
    volumes:
      - ../:/app
      - /app/node_modules
    depends_on:
      redis:
        condition: "service_healthy"
      db:
        condition: "service_healthy"
  nginx:
    image: nginx:stable-alpine3.17-slim
    container_name: reverse-proxy
    volumes:
      - ../packages/nginx/dev/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - client
      - server
