# use this to preview production build locally
version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root-user
      POSTGRES_PASSWORD: password123!
      PGPASSWORD: password123!
    ports:
      - 5432:5432
  redis:
    image: redis:6.2
    ports:
      - 6379:6379
  client:
    image: client-prod
    container_name: client-prod
    build:
      context: ../
      dockerfile: ./apps/client/Dockerfile
    restart: always
  api:
    image: server-prod
    container_name: server-prod
    build:
      context: ../
      dockerfile: ./apps/server/Dockerfile
    depends_on:
      redis:
        condition: "service_healthy"
      db:
        condition: "service_healthy"
    env_file:
      - ../apps/server/.env
  nginx:
    image: nginx-prod
    container_name: nginx-prod
    build:
      context: ../
      dockerfile: ./packages/nginx/docker/Dockerfile.preview
    ports:
      - 9090:80
    depends_on:
      - client
      - api
