# use this to preview production build locally
version: "3.9"

services:
  db:
    extends:
      file: docker-compose.common.yml
      service: db
    tty: true
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    extends:
      file: docker-compose.common.yml
      service: redis
    ports:
      - 6379:6379
  client:
    image: client-prod
    container_name: client-prod
    build:
      context: ../
      dockerfile: ./apps/client/Dockerfile
    volumes:
      - ../:/app
      - /app/node_modules
    restart: always
  api:
    extends:
      file: docker-compose.common.yml
      service: server-prod
    depends_on:
      redis:
        condition: "service_healthy"
      db:
        condition: "service_healthy"
    env_file:
      - ../apps/server/.env.development
    volumes:
      - ../:/app
      - /app/node_modules
  nginx:
    extends:
      file: docker-compose.common.yml
      service: preview-nginx
    ports:
      - 9090:80
    depends_on:
      - client
      - api
