version: "3.9"

services:
  client:
    image: client-dev
    container_name: client-dev
    build:
      # context: ../client
      context: ../
      # dockerfile: Dockerfile.dev
      dockerfile: ./apps/client/Dockerfile.dev
    volumes:
      # - ../client:/usr/src/app
      - ../apps/client:/usr/src/app
      - /usr/src/app/node_modules
  server:
    image: server-dev
    container_name: server-dev
    build:
      # context: ../server
      context: ../
      # dockerfile: Dockerfile.dev
      dockerfile: ./apps/server/Dockerfile.dev
    env_file:
      # - ../server/.env
      - ../apps/server/.env
    volumes:
      # - ../server:/usr/src/app
      - ../apps/server:/usr/src/app
      - /usr/src/app/node_modules
  nginx:
    image: nginx:stable-alpine3.17-slim
    container_name: reverse-proxy
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - client
