version: "3.9"

services:
  db:
    image: postgres:15 # Neon postgres version
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root-user
      POSTGRES_PASSWORD: password123!
      PGPASSWORD: password123!
    ports:
      - 5432:5432
  redis:
    image: redis:6.2
    # command: ["redis-server", "--bind", "redis", "--port", "6379"]
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - 6379:6379
  client:
    image: client-dev
    container_name: client-dev
    build:
      context: ../
      dockerfile: ./apps/client/Dockerfile.dev
    volumes:
      - ../:/app
      - /app/node_modules
  server:
    image: server-dev
    container_name: server-dev
    build:
      context: ../
      dockerfile: ./apps/server/Dockerfile.dev
    env_file:
      - ../apps/server/.env
    volumes:
      - ../:/app
      - /app/node_modules
    depends_on:
      redis:
        condition: "service_healthy"
      db:
        condition: "service_started"
  nginx:
    image: nginx:stable-alpine3.17-slim
    container_name: reverse-proxy
    volumes:
      - ../packages/nginx/dev/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - client
      - server
