name: "Propel Deployment"

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  super_secret: ${{ secrets.my_secret }}

jobs:
  build-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run build-push-images.sh
        run: |
          chmod +x ./scripts/build-push-images.sh
          ./scripts/build-push-images.sh
        # shell: bash

  deploy-api:
    needs: build-push-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run zip-bean-deploy.sh
        env:
          SERVICE_S3_BUCKET: ${{ secrets.SERVICE_S3_BUCKET }}
          SERVICE_ZIP_URL: ${{ secrets.SERVICE_ZIP_URL }}
        run: |
          chmod +x ./scripts/zip-bean-deploy.sh
          ./scripts/zip-bean-deploy.sh

  deploy-client:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run s3-sync.sh
        env:
          CLIENT_S3_BUCKET: ${{ secrets.CLIENT_S3_BUCKET }}
          CLOUDFRONT_DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}
        run: |
          chmod +x ./scripts/s3-sync.sh
          ./scripts/s3-sync.sh
