name: "Propel Deployment"

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

  workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/playwright.yml
    secrets: inherit
  build-push-images:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Run build-push-images.sh
        run: |
          chmod +x ./scripts/build-push-images.sh
          cd scripts && ./build-push-images.sh

  deploy-api:
    needs: build-push-images
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run zip-bean-deploy.sh
        env:
          SERVICE_S3_BUCKET: ${{ secrets.SERVICE_S3_BUCKET }}
          SERVICE_ZIP_URL: ${{ secrets.SERVICE_ZIP_URL }}
        run: |
          chmod +x ./scripts/zip-bean-deploy.sh
          cd scripts && ./zip-bean-deploy.sh

  # ideally would run after beanstalk deploy is successful
  deploy-client:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add prod url to client env
        run: |
          echo VITE_PROD_PROXY_URL=${{ secrets.PROD_API_URL }} > apps/client/.env.local

      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run s3-sync.sh
        env:
          CLIENT_S3_BUCKET: ${{ secrets.CLIENT_S3_BUCKET }}
          CLOUDFRONT_DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}
        run: |
          chmod +x ./scripts/s3-sync.sh
          cd scripts && ./s3-sync.sh
