name: Playwright Tests
on: [workflow_call, workflow_dispatch]

jobs:
  tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Add .env.local for API_URL
        run: |
          echo "VITE_PREVIEW_PROXY_URL=http://localhost:9090/api" > apps/client/.env.local

      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test --workspace=e2e
        env:
          PG_URL: ${{ secrets.PG_URL }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_PW: ${{ secrets.REDIS_PW }}
          REDIS_USERNAME: ${{ secrets.REDIS_USERNAME }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          IDLE_SESSION_LENGTH: ${{ secrets.IDLE_SESSION_LENGTH }}
          ABSOLUTE_SESSION_LENGTH: ${{ secrets.ABSOLUTE_SESSION_LENGTH }}
          PRE_AUTH_SESSION_LENGTH: ${{ secrets.PRE_AUTH_SESSION_LENGTH }}
          CSRF_SECRET: ${{ secrets.CSRF_SECRET }}
          PRE_AUTH_CSRF_SECRET: ${{ secrets.PRE_AUTH_CSRF_SECRET }}
          COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
          SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}
          RESEND_KEY: ${{ RESEND_KEY }}
          RECOVERY_EMAIL: ${{ secrets.RECOVERY_EMAIL }}
          VERIFY_EMAIL: ${{ secrets.VERIFY_EMAIL }}
          TESTMAIL_KEY: ${{ secrets.TESTMAIL_KEY }}
          TESTMAIL_ENDPOINT: ${{ secrets.TESTMAIL_ENDPOINT }}
          TESTMAIL_NAMESPACE: ${{ secrets.TESTMAIL_NAMESPACE }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: /apps/e2e/playwright-report/
          retention-days: 30
      # playwright passes sigkill to webserver, docker compose does not 'close' as a result
      - name: docker compose down
        run: docker compose -f .docker/docker-compose.playwright.yml down
